print("^2 [MIXAS AntiCheat] ^5 EntityConfig Refresh ^0")
EntityConfig = {}

EntityConfig.Commands = {
    EntityDeleteCommand = 'entitywipe', -- you can use this command in F8, chat or CMD
    CarDeleteCommand = 'carwipe', -- you can use this command in F8, chat or CMD
    PedDeleteCommand = 'pedwipe', -- you can use this command in F8, chat or CMD
}

EntityConfig.VehicleLimits = {
    VSL = false, -- it blocks cheater to spawn so many vehicles, if you have NPCs in your server make it false
    VehicleSpawnLimit = 4, -- limit number for VSL
    VSLDebug = true, -- when someone spawns vehicles more than limitation you will see it in CMD
    DistanceProtect = false,
    MaxSpawnDistance = 60,
}

EntityConfig.PedLimits = {
    PSL = false, -- it blocks cheater to spawn so many peds or NPCs, if you have NPCs in your server make it false
    PedSpawnLimit = 4, -- limit number for PSL
    PSLDebug = false -- when someone spawns peds or NPCs more than limitation you will see it in CMD
}

EntityConfig.EntityLimits = {
    ESL = false, -- it blocks cheater to spawn so many objects
    EntitySpawnLimit = 2, -- limit number for ESL
    ESLDebug = true -- when someone spawns objects more than limitation you will see it in CMD
}

EntityConfig.Invisible = {
    Detection = false, -- if true, it removes everything invisible(vehicles, props/objetcs etc.)
    Ban = false, -- if true, it bans whoever spawns something invisible
    Kick = true -- if true, it kicks whoever spawns something invisible
}


EntityConfig.BlacklistEntities = {
    BlacklistEntity = false, -- if true, it detects blacklisted entites below
    BlacklistedEntity = { -- type {kick or ban}
        {hash = GetHashKey("prop_fnclink_05crnr1"), type = "ban"},
        {hash = GetHashKey("xs_prop_hamburgher_wl"), type = "ban"},
        {hash = GetHashKey("xs_prop_plastic_bottle_wl"), type = "ban"},
        {hash = GetHashKey("prop_windmill_01"), type = "ban"},
        {hash = GetHashKey("p_spinning_anus_s"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_adj_flip_m"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_adj_flip_mb"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_adj_flip_s"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_adj_flip_sb"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_adj_hloop"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_adj_loop"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_jump_l"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_jump_m"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_jump_s"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_jump_xl"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_jump_xs"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_jump_xxl"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_multi_loop_rb"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_spiral_l"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_spiral_l_l"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_spiral_l_m"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_spiral_l_s"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_spiral_l_xxl"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_spiral_m"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_spiral_s"), type = "ban"},
        {hash = GetHashKey("stt_prop_ramp_spiral_xxl"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_track_dwuturn"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_track_dwslope30"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_track_start"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_track_hill2"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_huge_01"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_huge_02"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_huge_03"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_huge_04"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_huge_05"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_hump_01"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_hump_02"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_lrg1"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_lrg2"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_lrg3"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_mdm1"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_mdm2"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_mdm3"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_qp"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_qp2"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bblock_qp3"), type = "ban"},
        {hash = GetHashKey("prop_beach_fire"), type = "ban"},
        {hash = GetHashKey("prop_gas_pump_1a"), type = "ban"},
        {hash = GetHashKey("prop_gas_pump_1b"), type = "ban"},
        {hash = GetHashKey("prop_gas_pump_1c"), type = "ban"},
        {hash = GetHashKey("prop_gas_pump_1d"), type = "ban"},
        {hash = GetHashKey("prop_gas_pump_old2"), type = "ban"},
        {hash = GetHashKey("prop_gas_pump_old3"), type = "ban"},
        {hash = GetHashKey("prop_vintage_pump"), type = "ban"},
        {hash = GetHashKey("apa_mp_h_acc_box_trinket_01"), type = "ban"},
        {hash = GetHashKey("prop_roundbailer02"), type = "ban"},
        {hash = GetHashKey("prop_roundbailer01"), type = "ban"},
        {hash = GetHashKey("prop_container_05a"), type = "ban"},
        {hash = GetHashKey("stt_prop_stunt_bowling_ball"), type = "ban"},
        {hash = GetHashKey("apa_mp_h_acc_rugwoolm_03"), type = "ban"},
        {hash = GetHashKey("prop_container_ld2"), type = "ban"},
        {hash = GetHashKey("hei_prop_carrier_cargo_02a"), type = "ban"},
        {hash = GetHashKey("p_cablecar_s"), type = "ban"},
        {hash = GetHashKey("p_ferris_car_01"), type = "ban"},
        {hash = GetHashKey("prop_cj_big_boat"), type = "ban"},
        {hash = GetHashKey("prop_rock_4_big2"), type = "ban"},
        {hash = GetHashKey("prop_steps_big_01"), type = "ban"},
        {hash = GetHashKey("v_ilev_lest_bigscreen"), type = "ban"},
        {hash = GetHashKey("prop_carcreeper"), type = "ban"},
        {hash = GetHashKey("apa_mp_h_bed_double_09"), type = "ban"},
        {hash = GetHashKey("apa_mp_h_bed_wide_05"), type = "ban"},
        {hash = GetHashKey("prop_cattlecrush"), type = "ban"},
        {hash = GetHashKey("prop_cs_documents_01"), type = "ban"},
        {hash = GetHashKey("prop_ferris_car_01_lod1"), type = "ban"},
        {hash = GetHashKey("prop_construcionlamp_01"), type = "ban"},
        {hash = GetHashKey("prop_fncconstruc_01d"), type = "ban"},
        {hash = GetHashKey("prop_fncconstruc_02a"), type = "ban"},
        {hash = GetHashKey("p_dock_crane_cabl_s"), type = "ban"},
        {hash = GetHashKey("prop_dock_crane_01"), type = "ban"},
        {hash = GetHashKey("prop_dock_crane_02_cab"), type = "ban"},
        {hash = GetHashKey("prop_dock_float_1"), type = "ban"},
        {hash = GetHashKey("prop_dock_crane_lift"), type = "ban"},
        {hash = GetHashKey("apa_mp_h_bed_double_08"), type = "ban"},
        {hash = GetHashKey("csx_seabed_bldr4_"), type = "ban"},
        {hash = GetHashKey("imp_prop_impexp_sofabed_01a"), type = "ban"},
        {hash = GetHashKey("apa_mp_h_yacht_bed_01"), type = "ban"},
        {hash = GetHashKey("rhino"), type = "ban"},
        {hash = GetHashKey("oppressor"), type = "ban"},
        {hash = GetHashKey("oppressor2"), type = "ban"},
        {hash = GetHashKey("blimp2"), type = "ban"},
        {hash = GetHashKey("dingy"), type = "ban"},
        {hash = GetHashKey("blimp3"), type = "ban"},
        {hash = GetHashKey("a_m_y_acult_02"), type = "ban"},
        {hash = GetHashKey("limo2"), type = "ban"},
        {hash = GetHashKey("freightcont1"), type = "ban"},
        {hash = GetHashKey("freightcont2"), type = "ban"},
        {hash = GetHashKey("freightgrain"), type = "ban"},
        {hash = GetHashKey("cerberus3"), type = "ban"},
        {hash = GetHashKey("cerberus2"), type = "ban"},
        {hash = GetHashKey("cerberus"), type = "ban"},
        {hash = GetHashKey("phantom2"), type = "ban"},
        {hash = GetHashKey("savage"), type = "ban"},
        {hash = GetHashKey("hunter"), type = "ban"},
        {hash = GetHashKey("akula"), type = "ban"},
        {hash = GetHashKey("annihilator"), type = "ban"},
        {hash = GetHashKey("cutter"), type = "ban"},
        {hash = GetHashKey("barracks3"), type = "ban"},
        {hash = GetHashKey("barrage"), type = "ban"},
        {hash = GetHashKey("chernobog"), type = "ban"},
        {hash = GetHashKey("halftrack"), type = "ban"},
        {hash = GetHashKey("minitank"), type = "ban"},
        {hash = GetHashKey("scarab"), type = "ban"},
        {hash = GetHashKey("scarab2"), type = "ban"},
        {hash = GetHashKey("scarab3"), type = "ban"},
        {hash = GetHashKey("thruster"), type = "ban"},
        {hash = GetHashKey("trailersmall2"), type = "ban"},
        {hash = GetHashKey("brutus3"), type = "ban"},
        {hash = GetHashKey("monster3"), type = "ban"},
        {hash = GetHashKey("monster4"), type = "ban"},
        {hash = GetHashKey("monster5"), type = "ban"},
        {hash = GetHashKey("technical"), type = "ban"},
        {hash = GetHashKey("technical3"), type = "ban"},
        {hash = GetHashKey("technical2"), type = "ban"},
        {hash = GetHashKey("nightshark"), type = "ban"},
        {hash = GetHashKey("zhaba"), type = "ban"},
        {hash = GetHashKey("formula"), type = "ban"},
        {hash = GetHashKey("formula2"), type = "ban"},
        {hash = GetHashKey("scramjet"), type = "ban"},
        {hash = GetHashKey("vestra"), type = "ban"},
        {hash = GetHashKey("velum"), type = "ban"},
        {hash = GetHashKey("velum2"), type = "ban"},
        {hash = GetHashKey("trash2"), type = "ban"},
        {hash = GetHashKey("zr380"), type = "ban"},
        {hash = GetHashKey("zr3802"), type = "ban"},
        {hash = GetHashKey("zr3803"), type = "ban"},
        {hash = GetHashKey("raptor"), type = "ban"},
        {hash = GetHashKey("volatol"), type = "ban"},
        {hash = GetHashKey("voltic2"), type = "ban"},
        {hash = GetHashKey("tula"), type = "ban"},
        {hash = GetHashKey("strikeforce"), type = "ban"},
        {hash = GetHashKey("valkyrie2"), type = "ban"},
        {hash = GetHashKey("valkyrie"), type = "ban"},
        {hash = GetHashKey("hydra"), type = "ban"},
        {hash = GetHashKey("bombushka"), type = "ban"},
        {hash = GetHashKey("bruiser3"), type = "ban"},
        {hash = GetHashKey("bruiser2"), type = "ban"},
        {hash = GetHashKey("bruiser"), type = "ban"},
        {hash = GetHashKey("caracara"), type = "ban"},
        {hash = GetHashKey("dune5"), type = "ban"},
        {hash = GetHashKey("dune4"), type = "ban"},
        {hash = GetHashKey("dune3"), type = "ban"},
        {hash = GetHashKey("dune2"), type = "ban"},
        {hash = GetHashKey("openwheel1"), type = "ban"},
        {hash = GetHashKey("paragon2"), type = "ban"},
        {hash = GetHashKey("formula"), type = "ban"},
        {hash = GetHashKey("formula2"), type = "ban"},
        {hash = GetHashKey("blazer5"), type = "ban"},
        {hash = GetHashKey("slamvan4"), type = "ban"},
        {hash = GetHashKey("slamvan5"), type = "ban"},
        {hash = GetHashKey("slamvan6"), type = "ban"},
        {hash = GetHashKey("ruiner2"), type = "ban"},
        {hash = GetHashKey("dukes2"), type = "ban"},
        {hash = GetHashKey("dominator4"), type = "ban"},
        {hash = GetHashKey("dominator5"), type = "ban"},
        {hash = GetHashKey("dominator6"), type = "ban"},
        {hash = GetHashKey("handler"), type = "ban"},
        {hash = GetHashKey("vindicator"), type = "ban"},
        {hash = GetHashKey("wastelander"), type = "ban"},
        {hash = GetHashKey("ardent"), type = "ban"},
        {hash = -1404869155, type = "ban"},--FIB Build
        {hash = -685641702, type = "ban"},--unknown
        {hash = -759902142, type = "ban"},--city
        {hash = -2967811882, type = "ban"},--city
        {hash = -566160949, type = "ban"},--city
        {hash = -841438406, type = "ban"},--city
        {hash = -3821613641, type = "ban"},--city
        {hash = -3957771795, type = "ban"}--city
    }
}



EntityConfig.Deletes = {
    AllPedDelete = false, -- it deletes all peds
    AllPropDelete = false, -- it deletes all props
    AllCarDelete = false, -- it deletes all vehicles
}

EntityConfig.WhitelistEntitys = {
    PropWhitelist = false, -- if true, you can whitelist entities below so everyone will be able to use/spawn it
    PropKick = false,
    PropBan = false,
    WLProps = { -- here you can add or remove whitelisted objects
        1760825203,
        3258159972,
        3420629148,
        2518469636,
        386059801,
        2322124445,
        3182194296,
        0,
        3792764623,
        4078088296,
        4238628018,
        45840177,
        3646908049,
        1158698200,
        2724401750,
        3553022755,
        2366942797,
        3292998251,
        1302435108,
        3362210457,
        3745732117,
        3577824813,
        1020618269,
        2009246193,
        -1354005816,
        683570518,
        -2054442544,
        746336278,
        1874679314,
        1676901836,
        -1109340972,
        1847598393,
        -969349845,
        -1528307545,
        -708789241,
        76092178,
        61087258,
        -645296272,
        -1016640704,
        680380202,
        944959446,
        -517243780,
        -1170050911,
        -692093509,
        -917746868,
        1203231469,
        -461945070,
        -1623189257,
        -1585232418,
        1407197773,
        -678752633,
        -960996301,
        -1863407086,
        880595258,
        -447760697,
        600913159,
        1217034051,
        1471171713,
        -1296547421,
        1407268736,
        4117863282,
        765087784,
        1039360035,
        1336576410,
        -1249748547,
        -994740387,
        272925894,
        -781595832,
        -1676901836,
        -177104014,
        -741944541,
        -1972842851,
        1792816905,
        1603932804,
        3872089630,
        -746954904,
        -874338148,
        -113902346,
        250374685,
        686990798,
        463086472, 
        29402038,
        2017086435, 
        -598185919,  
        1368637848,
        1760825203,
        -74194454,
    }
}

